package org.training.leisure.swimmingpool;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InsertPeriodEnum implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public InsertPeriodEnum() {
    }

}