package org.training.leisure.swimmingpool;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InsertPeriod implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String enumValue;

   public InsertPeriod()
   {
   }

   public java.lang.String getEnumValue()
   {
      return this.enumValue;
   }

   public void setEnumValue(java.lang.String enumValue)
   {
      this.enumValue = enumValue;
   }

   public InsertPeriod(java.lang.String enumValue)
   {
      this.enumValue = enumValue;
   }
@Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("InsertPeriod{");
        sb.append("enumValue=").append(enumValue);
        sb.append('}');
        return sb.toString();
    }
}