package org.training.leisure.swimmingpool;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InsertPeriodEnum implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String enumName;

   public InsertPeriodEnum()
   {
   }

   public java.lang.String getEnumName()
   {
      return this.enumName;
   }

   public void setEnumName(java.lang.String enumName)
   {
      this.enumName = enumName;
   }

   public InsertPeriodEnum(java.lang.String enumName)
   {
      this.enumName = enumName;
   }

}