package org.training.leisure.swimmingpool;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StartProcess implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String processId;

   public StartProcess()
   {
   }

   public java.lang.String getProcessId()
   {
      return this.processId;
   }

   public void setProcessId(java.lang.String processId)
   {
      this.processId = processId;
   }

   public StartProcess(java.lang.String processId)
   {
      this.processId = processId;
   }

}